DROP TABLE BI_MDM.TB_DM_BSNSS_UNT_SLSFRC;	

CREATE TABLE BI_MDM.TB_DM_BSNSS_UNT_SLSFRC
(	SK_BSNSS_UNT VARCHAR2(250) PRIMARY KEY,
	DS_BSNSS_UNT VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

  SELECT * FROM BI_MDM.TB_DM_BSNSS_UNT_SLSFRC
