DROP TABLE BI_MDM.TB_DM_RGN_SLSFRC;	

CREATE TABLE BI_MDM.TB_DM_RGN_SLSFRC (
	SK_RGN_SLSFRC VARCHAR2(250) PRIMARY KEY,
	DS_RGN_SLSFRC VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

    
SELECT * from BI_MDM.TB_DM_RGN_SLSFRC