DROP TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_BRIC;

CREATE TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_BRIC
(
	brick_cod VARCHAR2(9),
	brick_desc VARCHAR2(120),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFT_BRA_DDDMIX_BRIC