DROP TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_MOL;

CREATE TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_MOL
(
	FCC_COD VARCHAR2(10),
	MOL_DESC VARCHAR2(250),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFT_BRA_DDDMIX_MOL