DROP TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_PFLGS;

CREATE TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_PFLGS
(
	FCC VARCHAR2(10),
	BRAND VARCHAR2(64),
	COD_ABCFAR VARCHAR2(10),
	CONTROLADO VARCHAR2(1),
	INTE VARCHAR2(128),
	RX_OTC_HBN VARCHAR2(16),
	FAB_NAC_MU VARCHAR2(16),
	FITOTERAPE VARCHAR2(1),
	CADEIA_FRI VARCHAR2(1),
	FPOP VARCHAR2(1),
	KIT VARCHAR2(1),
	PAIS_ORIGE VARCHAR2(64),
	GMRS VARCHAR2(1),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFT_BRA_DDDMIX_PFLGS