DROP TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_PKML;

CREATE TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_PKML
(
	SUBS_COD VARCHAR2(6),
	fcc_cod VARCHAR2(10),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFT_BRA_DDDMIX_PKML