DROP TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_PRIC;

CREATE TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_PRIC
(
	period_cod VARCHAR2(8),
	fcc_cod VARCHAR2(10),
	pr_list VARCHAR2(15),
	pr_ppp VARCHAR2(15),
	pr_ch VARCHAR2(15),
	pr_ch_ppp VARCHAR2(15),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFT_BRA_DDDMIX_PRIC