DROP TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_PROD;

CREATE TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_PROD
(
	prod_cod VARCHAR2(10),
	Prod_desc VARCHAR2(50),
	manu_cod VARCHAR2(5),
	prod_lnch VARCHAR2(8),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFT_BRA_DDDMIX_PROD