DROP TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_RATE;

CREATE TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_RATE
(
	Period_Cod VARCHAR2(8),
	Rate VARCHAR2(9),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFT_BRA_DDDMIX_RATE