DROP TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_REGI;

CREATE TABLE BI.TB_WRK_FFFT_BRA_DDDMIX_REGI
(
	Sale_cod VARCHAR2(1),
	Regi_cod VARCHAR2(3),
	Regi_desc VARCHAR2(50),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFT_BRA_DDDMIX_REGI