DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_APP;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_APP
(	PACK_CD VARCHAR2(10),
	PACK_DESC VARCHAR2(150),
	PRODUCT_CONCTR_CD  VARCHAR2(50),
	APP1_CD VARCHAR2(50),
	APP1_DESC VARCHAR2(150),
	APP2_CD VARCHAR2(50),
	APP2_DESC VARCHAR2(150),
	APP3_CD VARCHAR2(50),
	APP3_DESC VARCHAR2(150),
	DT_ULT_ATZ timestamp
);

SELECT
APP3_CD,
COUNT(*)
FROM (
SELECT 
DISTINCT
APP3_CD,
APP2_CD,
APP1_CD
FROM BI.TB_WRK_PBS_FFF_BRA_GPS_APP
ORDER BY APP3_CD ASC )
GROUP BY APP3_CD
ORDER BY COUNT(*) DESC


SELECT DISTINCT APP3_CD FROM BI.TB_WRK_PBS_FFF_BRA_GPS_APP
ORDER BY 1 DESC




