DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_CHANNEL;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_CHANNEL
(	CHANNEL_CD VARCHAR2(2),
	CHANNEL_DESC VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_CHANNEL