DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_CONCTR;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_CONCTR
(	PACK_CD VARCHAR2(50),
	PACK_DESC VARCHAR2(100),
	PRODUCT_DESC VARCHAR2(100),
	PRODUCT_CONCTR_CD VARCHAR2(100),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_CONCTR