DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_DOCTOR_;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_DOCTOR_
(	DOCTOR_DISPENSED_CATEGORY_CD VARCHAR2(5),
	DOCTOR_DISPENSED_CATEGORY_DESC VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_DOCTOR_
