DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_DOC_RX;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_DOC_RX
(	DOCTOR_RX_CATEGORY_CD VARCHAR2(5),
	DOCTOR_RX_CATEGORY_DESC VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_DOC_RX