DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_IMS_TER;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_IMS_TER
(	IMS_TERRITORY_CD VARCHAR2(250),
	IMS_TERRITORY_DESC VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_IMS_TER