DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_MARKETS;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_MARKETS
(	MARKET_CD VARCHAR2(250),
	MARKET_DESC VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_MARKETS