DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS
(	PERIOD_CD VARCHAR2(250),
	DOCTOR_CD VARCHAR2(250),
	IMS_BRICK_CD VARCHAR2(250),
	ZIP_CD  VARCHAR2(250),
	IMS_TERRITORY_CD  VARCHAR2(250),
	SALESFORCE_CD  VARCHAR2(250),
	TERRITORY_CD  VARCHAR2(250),
	MARKET_CD  VARCHAR2(250),
	PSCR_PRODUCT_CONCTR_CD  VARCHAR2(250),
	DISPENSED_PACK_CD  VARCHAR2(250),
	SWITCH_CD VARCHAR2(250),
	CHANNEL_CD  VARCHAR2(250),
	RX_COUNT  VARCHAR2(250),
	DISPENSED_QTY  VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT COUNT(*) FROM BI.TB_WRK_PBS_FFF_BRA_GPS

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS