DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_PERIODS;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_PERIODS
(	PERIOD_CD VARCHAR2(10),
	PERIOD_DESC VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_PERIODS