DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_PRESCR_;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_PRESCR_
(	PSCR_PRODUCT_CONCTR_CD VARCHAR2(250),
	PSCR_PRODUCT_CONCTR_DESC VARCHAR2(250),
	PRESCRIBED_PRODUCT_CD VARCHAR2(250),
	PRESCRIBED_PRODUCT_DESC VARCHAR2(250),
	MANUFACTURER_CD VARCHAR2(250),
	MANUFACTURER_DESC VARCHAR2(250),
	PRODUCT_LAUNCH VARCHAR2(250),
	MARK_TYPE VARCHAR2(250),
	BRAND_NAME VARCHAR2(250),
	STGH_VALUE VARCHAR2(250),
	STGH_MEASURE VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_PRESCR_