DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_SALESFO;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_SALESFO
(	SALESFORCE_CD VARCHAR2(250),
	BUSINESS_UNIT VARCHAR2(250),
	REGION_CD VARCHAR2(250),
	DISTRICT_CD VARCHAR2(250),
	TERRITORY_CD VARCHAR2(250),
	REGION_DESC VARCHAR2(250),
	DISTRICT_DESC VARCHAR2(250),
	TERRITORY_DESC  VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_SALESFO

SELECT
SALESFORCE_CD||TERRITORY_CD,COUNT(*)
FROM BI.TB_WRK_PBS_FFF_BRA_GPS_SALESFO
GROUP BY SALESFORCE_CD||TERRITORY_CD
HAVING COUNT(*) > 1


SELECT DISTINCT region_cd,region_desc,salesforce_cd FROM BI.TB_WRK_PBS_FFF_BRA_GPS_SALESFO