DROP TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_SWITCH;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_GPS_SWITCH
(	SWITCH_CD VARCHAR2(250),
	SWITCH_DESC VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_GPS_SWITCH