DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_CORP;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_CORP
(
	CORP_COD VARCHAR2(5),
	CORP_DESC VARCHAR2(50),
	CORP_RES VARCHAR2(3),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_CORP