DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_MANU;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_MANU
(
	MANU_COD VARCHAR2(5),
	manu_desc VARCHAR2(50),
	MANU_SHORT VARCHAR2(3),
	CORP_COD VARCHAR2(5),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_MANU