DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_MOL;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_MOL
(
	FCC_COD VARCHAR2(10),
	MOL_DESC VARCHAR2(250),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_MOL