DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_NEC;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_NEC
(
	nec4_cod VARCHAR2(5),
	nec4_desc VARCHAR2(50),
	nec3_cod VARCHAR2(4),
	nec3_desc VARCHAR2(50),
	nec2_cod VARCHAR2(3),
	nec2_desc VARCHAR2(50),
	nec1_cod VARCHAR2(2),
	nec1_desc VARCHAR2(50),
	mkt_sec VARCHAR2(6),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_NEC

