DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_OUTL;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_OUTL
(
	OUTLET_cod VARCHAR2(10),
	outlet_des VARCHAR2(50),
	OUTLET_add VARCHAR2(120),
	chan_cod VARCHAR2(4),
	BRICK_cod VARCHAR2(10),
	CNPJ VARCHAR2(14),
	COMPLE_C VARCHAR2(50),
	BAIRRO VARCHAR2(50),
	LOGRADOURO VARCHAR2(50),
	TELEFONE VARCHAR2(50),
	CEP VARCHAR2(8),
	Cidade VARCHAR2(50),
	UF VARCHAR2(2),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_OUTL

SELECT DISTINCT BRICK_COD FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_OUTL
WHERE BRICK_COD NOT IN (
SELECT SK_BRCK FROM BI_MDM.TB_DM_BRCK)

