DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_PACK;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_PACK
(
	pack_cod VARCHAR2(10),
	pack_desc VARCHAR2(90),
	fcc_cod VARCHAR2(10),
	prod_cod VARCHAR2(10),
	EAN VARCHAR2(15),
	pack_lnch VARCHAR2(10),
	Class4_cod VARCHAR2(6),
	nec4_cod VARCHAR2(5),
	App3_cod VARCHAR2(3),
	mark_code VARCHAR2(1),
	std_fact VARCHAR2(15),
	dsg_fact VARCHAR2(15),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_PACK