DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_PROV;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_PROV
(
	prov_cod VARCHAR2(10),
	Prov_desc VARCHAR2(50),
	CNPJ VARCHAR2(14),
	PROV_TYPE VARCHAR2(30),
	PROV_STATE VARCHAR2(2),
	PROV_CITY VARCHAR2(50),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_PROV