DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_REPO;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_REPO
(
	PROD_Code VARCHAR2(10),
	FCC_Code VARCHAR2(10),
	report_cod VARCHAR2(2),
	report_des VARCHAR2(50),
	colu_cod VARCHAR2(5),
		DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_REPO