DROP TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_SALE;

CREATE TABLE BI.TB_WRK_FFFC_BRA_MDTRMMIX_SALE
(
	Sale_Cod VARCHAR2(1),
	SALE_DESC VARCHAR2(50),	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_FFFC_BRA_MDTRMMIX_SALE