DROP TABLE BI_MDM.TB_FT_DDD;

CREATE TABLE BI_MDM.TB_FT_DDD
(
SK_PFLGS VARCHAR2(10),
SK_PCK VARCHAR2(10),
SK_BRCK VARCHAR2(9),
SK_RGN	VARCHAR2(3),
SK_TRR	VARCHAR2(9),
SK_TMP_PRD INT,
SK_TMP_APRC INT,
SK_CHN VARCHAR2(4),
FLG_CL_LT	VARCHAR2(1),
VL_QT_VND	INT,
VL_QT_TOT_VND	INT,
DT_ULT_ATZ timestamp
);


ALTER TABLE BI_MDM.TB_FT_DDD ADD CONSTRAINT SK_PCK_DDD
    FOREIGN KEY (SK_PCK)
    REFERENCES BI_MDM.TB_DM_PCK (SK_PCK)
    
ALTER TABLE BI_MDM.TB_FT_DDD ADD CONSTRAINT SK_PFLGS_DDD
    FOREIGN KEY (SK_PFLGS)
    REFERENCES BI_MDM.TB_DM_PFLGS (SK_PFLGS)
    
ALTER TABLE BI_MDM.TB_FT_DDD ADD CONSTRAINT SK_RGN_DDD
    FOREIGN KEY (SK_RGN)
    REFERENCES BI_MDM.TB_DM_RGN (SK_RGN)
    
ALTER TABLE BI_MDM.TB_FT_DDD ADD CONSTRAINT SK_TMP_PRD_DDD
    FOREIGN KEY (SK_TMP_PRD)
    REFERENCES BI_MDM.TB_DM_TMP (SK_TMP)

ALTER TABLE BI_MDM.TB_FT_DDD ADD CONSTRAINT SK_TMP_APRC_DDD
    FOREIGN KEY (SK_TMP_APRC)
    REFERENCES BI_MDM.TB_DM_TMP (SK_TMP)    
    
ALTER TABLE BI_MDM.TB_FT_DDD ADD CONSTRAINT SK_TRR_DDD
    FOREIGN KEY (SK_TRR)
    REFERENCES BI_MDM.TB_DM_TRR (SK_TRR)

ALTER TABLE BI_MDM.TB_FT_DDD ADD CONSTRAINT SK_BRCK_DDD
    FOREIGN KEY (SK_BRCK)
    REFERENCES BI_MDM.TB_DM_BRCK (SK_BRCK)    
    
ALTER TABLE BI_MDM.TB_FT_DDD ADD CONSTRAINT SK_CHN_DDD
    FOREIGN KEY (SK_CHN)
    REFERENCES BI_MDM.TB_DM_CHN (SK_CHN)    
    
    
    SELECT count(*) FROM BI_MDM.TB_FT_DDD -- 75 156 
    
