DROP TABLE BI_MDM.TB_DM_PRD;

CREATE TABLE BI_MDM.TB_DM_PRD
(
	SK_PRD	VARCHAR2(10) PRIMARY KEY,
	DS_PRD	VARCHAR2(50),
	SK_MNU	VARCHAR2(5),
	DS_PRD_LNCH	VARCHAR2(8),
	DT_ULT_ATZ timestamp
);
    

ALTER TABLE BI_MDM.TB_DM_PRD ADD CONSTRAINT FK_SK_MMU
    FOREIGN KEY (SK_MNU)
    REFERENCES BI_MDM.TB_DM_MNU (SK_MNU)

ALTER TABLE BI_MDM.TB_DM_PRD DROP CONSTRAINT FK_SK_MMU
    
SELECT * FROM BI_MDM.TB_DM_PRD

INSERT INTO BI_MDM.TB_DM_PRD VALUES ('0000000000','N/A','00000','00000000',SYSDATE)

COMMIT