DROP TABLE BI_MDM.TB_DM_PCK;

CREATE TABLE BI_MDM.TB_DM_PCK
(
	SK_PCK	VARCHAR2(10) PRIMARY KEY,
	DS_PCK	VARCHAR2(90),
	SK_MOL	VARCHAR2(10),
	SK_PRD	VARCHAR2(10),
	DS_EAN	VARCHAR2(15),
	DS_PCK_LNCH	VARCHAR2(10),
	SK_CLS4	VARCHAR2(6),
	SK_NEC4	VARCHAR2(5),
	SK_APP3	VARCHAR2(3),
	FLG_MRK_CD	VARCHAR2(1),
	DS_STG_FCT	VARCHAR2(15),
	DS_DSG_FCT	VARCHAR2(15),
	DT_ULT_ATZ timestamp
);

ALTER TABLE BI_MDM.TB_DM_PCK ADD CONSTRAINT FK_SK_MOL
    FOREIGN KEY (SK_MOL)
    REFERENCES BI_MDM.TB_DM_MOL (SK_MOL)
    
ALTER TABLE BI_MDM.TB_DM_PCK ADD CONSTRAINT FK_SK_PRD_PCK
    FOREIGN KEY (SK_PRD)
    REFERENCES BI_MDM.TB_DM_PRD (SK_PRD)

ALTER TABLE BI_MDM.TB_DM_PCK ADD CONSTRAINT FK_SK_CLS4
    FOREIGN KEY (SK_CLS4)
    REFERENCES BI_MDM.TB_DM_CLS (SK_CLS4)    

ALTER TABLE BI_MDM.TB_DM_PCK ADD CONSTRAINT FK_SK_NEC4
    FOREIGN KEY (SK_NEC4)
    REFERENCES BI_MDM.TB_DM_NEC (SK_NEC4)    

ALTER TABLE BI_MDM.TB_DM_PCK ADD CONSTRAINT FK_SK_APP3
    FOREIGN KEY (SK_APP3)
    REFERENCES BI_MDM.TB_DM_APP (SK_APP3)       

    
SELECT * FROM BI_MDM.TB_DM_PCK
ORDER BY DT_ULT_ATZ DESC
