DROP TABLE BI_MDM.TB_DM_CHN;

CREATE TABLE BI_MDM.TB_DM_CHN
(
	SK_CHN VARCHAR2(9) PRIMARY KEY,
	DS_CHN VARCHAR2(50),
	SK_GR VARCHAR2(10),
	DS_GR VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_CHN
ORDER BY SK_CHN ASC