DROP TABLE BI_MDM.TB_DM_SBS;

CREATE TABLE BI_MDM.TB_DM_SBS
(
	SK_SBS	VARCHAR2(6) PRIMARY KEY,
	DS_SBS	VARCHAR2(70),
	SK_FML	VARCHAR2(4),
	DS_FML	VARCHAR2(50),
	SK_SBFML	VARCHAR2(6),
	DS_SBFML	VARCHAR2(50),
	DT_ULT_ATZ timestamp
);
    
SELECT * FROM BI_MDM.TB_DM_SBS