DROP TABLE BI_MDM.TB_DM_MOL;

CREATE TABLE BI_MDM.TB_DM_MOL
(
	SK_MOL	VARCHAR2(10) PRIMARY KEY,
	DS_MOL	VARCHAR2(250),
	DT_ULT_ATZ timestamp
);


SELECT * FROM BI_MDM.TB_DM_MOL
ORDER BY 1 ASC

INSERT INTO BI_MDM.TB_DM_MOL VALUES ('0000000000','N/A',SYSDATE)

COMMIT