DROP TABLE BI_MDM.TB_DM_PKML;

CREATE TABLE BI_MDM.TB_DM_PKML
(
	SK_PKML	VARCHAR2(16) PRIMARY KEY,
	SK_SBS	VARCHAR2(6),
	SK_MOL VARCHAR2(10),
	DT_ULT_ATZ timestamp
);


ALTER TABLE BI_MDM.TB_DM_PKML ADD CONSTRAINT FK_SK_SBS
    FOREIGN KEY (SK_SBS)
    REFERENCES BI_MDM.TB_DM_SBS (SK_SBS)

ALTER TABLE BI_MDM.TB_DM_PKML ADD CONSTRAINT FK_SK_MOL_PKML
    FOREIGN KEY (SK_MOL)
    REFERENCES BI_MDM.TB_DM_MOL (SK_MOL)
    
    
SELECT * FROM BI_MDM.TB_DM_PKML