DROP TABLE BI_MDM.TB_DM_SLS;

CREATE TABLE BI_MDM.TB_DM_SLS
(
	SK_SLS	VARCHAR2(1) PRIMARY KEY,
	DS_SLS	VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

    
SELECT * FROM BI_MDM.TB_DM_SLS

INSERT INTO BI_MDM.TB_DM_SLS VALUES ('0','N/A',SYSDATE)

COMMIT