DROP TABLE BI_MDM.TB_DM_DST;

CREATE TABLE BI_MDM.TB_DM_DST
(
	SK_DST	VARCHAR2(8) PRIMARY KEY,
	DS_DST	VARCHAR2(50),
	SK_RGN	VARCHAR2(3),
	SK_SLS	VARCHAR2(1),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_DST
ORDER BY sK_dst asc