DROP TABLE BI_MDM.TB_DM_PFLGS;

CREATE TABLE BI_MDM.TB_DM_PFLGS
(
	SK_PFLGS	VARCHAR2(10) PRIMARY KEY,
	DS_BRAND	VARCHAR2(64),
	DS_COD_ABCFAR	VARCHAR2(10),
	FLG_CNTRLD	VARCHAR2(1),
	DS_INTE	VARCHAR2(128),
	SG_RX_OTC_HBN	VARCHAR2(16),
	DS_FAB_NAC_MU	VARCHAR2(16),
	FLG_FTTRP	VARCHAR2(1),
	FLG_CD_FR	VARCHAR2(1),
	FLG_FPOP	VARCHAR2(1),
	FLG_KIT	VARCHAR2(1),
	DS_PAIS_ORIGE	VARCHAR2(64),
	SG_GMRS	VARCHAR2(1),
	DT_ULT_ATZ timestamp
);
    
    
SELECT * FROM BI_MDM.TB_DM_PFLGS