DROP TABLE BI_MDM.TB_DM_PRV;

CREATE TABLE BI_MDM.TB_DM_PRV
(
	SK_PRV	VARCHAR2(10) PRIMARY KEY,
	DS_PRV	VARCHAR2(50),
	DS_CNPJ	VARCHAR2(14),
	DS_PRV_TP	VARCHAR2(30),
	DS_ESTD	VARCHAR2(2),
	DS_CDD	VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

    
SELECT * FROM BI_MDM.TB_DM_PRV