DROP TABLE BI_MDM.TB_DM_APP;

CREATE TABLE BI_MDM.TB_DM_APP
(
	SK_APP3 VARCHAR2(3) PRIMARY KEY,
	DS_APP3 VARCHAR2(50),
	SK_APP2 VARCHAR2(2),
	DS_APP2 VARCHAR2(50),
	SK_APP1 VARCHAR2(1),
	DS_APP1 VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_APP
ORDER BY SK_APP3 ASC