DROP TABLE BI_MDM.TB_DM_MNU;

CREATE TABLE BI_MDM.TB_DM_MNU
(
	SK_MNU	VARCHAR2(5) PRIMARY KEY,
	DS_MNU	VARCHAR2(50),
	SG_MNU	VARCHAR2(3),
	SK_CRP	VARCHAR2(5),
	DT_ULT_ATZ timestamp
);

ALTER TABLE BI_MDM.TB_DM_MNU ADD CONSTRAINT FK_SK_CRP
    FOREIGN KEY (SK_CRP)
    REFERENCES BI_MDM.TB_DM_CRP (SK_CRP)


SELECT * FROM BI_MDM.TB_DM_MNU

INSERT INTO BI_MDM.TB_DM_MNU VALUES ('00000','N/A','N/A','00000',SYSDATE)

COMMIT