DROP TABLE BI_MDM.TB_DM_TRR;

CREATE TABLE BI_MDM.TB_DM_TRR
(
	SK_TRR	VARCHAR2(9) PRIMARY KEY,
	DS_TRR	VARCHAR2(50),
	SK_SLS	VARCHAR2(1),
	SK_RGN	VARCHAR2(3),
	SK_DST	VARCHAR2(8),
	DT_ULT_ATZ timestamp
);

ALTER TABLE BI_MDM.TB_DM_TRR ADD CONSTRAINT FK_SK_SLS
    FOREIGN KEY (SK_SLS)
    REFERENCES BI_MDM.TB_DM_SLS (SK_SLS)

ALTER TABLE BI_MDM.TB_DM_TRR ADD CONSTRAINT FK_SK_RGN
    FOREIGN KEY (SK_RGN)
    REFERENCES BI_MDM.TB_DM_RGN (SK_RGN)
    
ALTER TABLE BI_MDM.TB_DM_TRR ADD CONSTRAINT FK_SK_DST
    FOREIGN KEY (SK_DST)
    REFERENCES BI_MDM.TB_DM_DST (SK_DST)    

    
    
    
SELECT * FROM BI_MDM.TB_DM_TRR



