DROP TABLE BI_MDM.TB_DM_CLS;

CREATE TABLE BI_MDM.TB_DM_CLS
(
	SK_CLS4	 VARCHAR2(6) PRIMARY KEY,
	DS_CLS4	VARCHAR2(50),
	SK_CLS3	VARCHAR2(4),
	DS_CLS3	VARCHAR2(50),
	SK_CLS2	VARCHAR2(3),
	DS_CLS2	VARCHAR2(50),
	SK_CLS1	VARCHAR2(1),
	SL_CLS1	VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_CLS

INSERT INTO BI_MDM.TB_DM_CLS
VALUES
('00000','N/A','0000','N/A','000','N/A','0','N/A',SYSDATE)

COMMIT