DROP TABLE BI_MDM.TB_DM_OUTL;

CREATE TABLE BI_MDM.TB_DM_OUTL
(
	SK_OUTL	VARCHAR2(10) PRIMARY KEY,
	DS_OUTL	VARCHAR2(50),
	DS_ENDR	VARCHAR2(120),
	SK_CHN	VARCHAR2(4),
	SK_BRCK	VARCHAR2(10),
	DS_CNPJ	VARCHAR2(14),
	DS_ENDR_COMPLMNT VARCHAR2(50),
	DS_BRRO	VARCHAR2(50),
	DS_TP_ENDR	VARCHAR2(50),
	DS_TLFN	VARCHAR2(50),
	DS_CEP	VARCHAR2(8),
	DS_CDD	VARCHAR2(50),
	DS_UF	VARCHAR2(2),
	DT_ULT_ATZ timestamp
);

ALTER TABLE BI_MDM.TB_DM_OUTL ADD CONSTRAINT FK_SK_CHN
    FOREIGN KEY (SK_CHN)
    REFERENCES BI_MDM.TB_DM_CHN (SK_CHN)

ALTER TABLE BI_MDM.TB_DM_OUTL ADD CONSTRAINT FK_SK_BRCK
    FOREIGN KEY (SK_BRCK)
    REFERENCES BI_MDM.TB_DM_BRCK (SK_BRCK)    
    

SELECT * FROM BI_MDM.TB_DM_OUTF