DROP TABLE BI_MDM.TB_FT_MDTR_MNSL;

CREATE TABLE BI_MDM.TB_FT_MDTR_MNSL
(
SK_OUTL	VARCHAR2(10),
SK_PFLGS	VARCHAR2(10),
SK_PCK VARCHAR2(10),
SK_PRV	VARCHAR2(10),
SK_RGN	VARCHAR2(3),
SK_TRR	VARCHAR2(9),
SK_TMP_PRD INT,
SK_TMP_APRC INT,
FLG_CL_LT	VARCHAR2(1),
VL_QT_VND	INT,
VL_QT_TOT_VND	INT,
DT_ULT_ATZ timestamp
);


ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL ADD CONSTRAINT SK_PCK
    FOREIGN KEY (SK_PCK)
    REFERENCES BI_MDM.TB_DM_PCK (SK_PCK)

ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL ADD CONSTRAINT SK_OUTL
    FOREIGN KEY (SK_OUTL)
    REFERENCES BI_MDM.TB_DM_OUTL (SK_OUTL)
    
ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL ADD CONSTRAINT SK_PFLGS
    FOREIGN KEY (SK_PFLGS)
    REFERENCES BI_MDM.TB_DM_PFLGS (SK_PFLGS)
    
ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL ADD CONSTRAINT SK_SK_PRV
    FOREIGN KEY (SK_PRV)
    REFERENCES BI_MDM.TB_DM_PRV (SK_PRV)

ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL ADD CONSTRAINT SK_RGN
    FOREIGN KEY (SK_RGN)
    REFERENCES BI_MDM.TB_DM_RGN (SK_RGN)
    
ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL ADD CONSTRAINT SK_TMP_PRD
    FOREIGN KEY (SK_TMP_PRD)
    REFERENCES BI_MDM.TB_DM_TMP (SK_TMP)

ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL ADD CONSTRAINT SK_TMP_APRC
    FOREIGN KEY (SK_TMP_APRC)
    REFERENCES BI_MDM.TB_DM_TMP (SK_TMP)    
    
ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL ADD CONSTRAINT SK_TRR
    FOREIGN KEY (SK_TRR)
    REFERENCES BI_MDM.TB_DM_TRR (SK_TRR)
    
--ALTER TABLE BI_MDM.TB_FT_MDTR_MNSL DROP CONSTRAINT SK_TMP
    
SELECT SK_TMP_PRD,COUNT(*) FROM BI_MDM.TB_FT_MDTR_MNSL
GROUP BY SK_TMP_PRD

SELECT * FROM BI_CNTRL_CRG.C$_0TB_STG_FT_MDTR_MNSL