DROP TABLE BI.TB_STG_FT_MDTR_MNSL;

TRUNCATE TABLE BI.TB_STG_FT_MDTR_MNSL;


CREATE TABLE BI.TB_STG_FT_MDTR_MNSL
(
SK_OUTL	VARCHAR2(10),
SK_PFLGS	VARCHAR2(10),
SK_PRV	VARCHAR2(10),
SK_RGN	VARCHAR2(3),
SK_TRR	VARCHAR2(9),
SK_TMP_APRC INT,
SK_TMP_PRD INT,
FLG_CL_LT	VARCHAR2(1),
VL_QT_VND	INT,
VL_QT_TOT_VND	INT,
DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_STG_FT_MDTR_MNSL

SELECT DISTINCT 
nr_anomes,
round( months_between(last_day(TRUNC(Sysdate-60,'MM')),trunc(DS_DATA,'MM') ) )
FROM BI_MDM.TB_DM_TMP
ORDER BY nr_anomes DESC


UPDATE BI_MDM.TB_DM_TMP
SET DS_ORD_MES = round( months_between(last_day(TRUNC(Sysdate-60,'MM')),trunc(DS_DATA,'MM') ) )

COMMIT


SELECT mes,count(*) FROM BI.TB_STG_FT_MDTR_MNSL
GROUP BY mes
ORDER BY mes desc


SELECT DISTINCT
DS_ORD_MES,
NR_ANOMES
FROM
BI_MDM.TB_DM_TMP
ORDER BY DS_ORD_MES



 SELECT TO_NUMBER(TO_CHAR(SYSDATE-60,'YYYYMM')||'01') FROM DUAL
 
 
 
 
 
 select	/*+APPEND*/ 
	TB_STG_FT_MDTR_MNSL_1.SK_OUTL	AS SK_OUTL,
	TB_STG_FT_MDTR_MNSL_1.SK_PFLGS	AS SK_PFLGS,
	TB_STG_FT_MDTR_MNSL_1.SK_PRV	AS SK_PRV,
	TB_STG_FT_MDTR_MNSL_1.SK_RGN	AS SK_RGN,
	TB_STG_FT_MDTR_MNSL_1.SK_TRR	AS SK_TRR,
	TB_STG_FT_MDTR_MNSL_1.SK_TMP_APRC	AS SK_TMP_APRC,
	TB_STG_FT_MDTR_MNSL_1.SK_TMP_PRD	AS SK_TMP_PRD,
	TB_STG_FT_MDTR_MNSL_1.FLG_CL_LT	AS FLG_CL_LT,
	TB_STG_FT_MDTR_MNSL_1.VL_QT_VND	AS VL_QT_VND,
	TB_STG_FT_MDTR_MNSL_1.VL_QT_TOT_VND	AS VL_QT_TOT_VND
from	BI.TB_STG_FT_MDTR_MNSL TB_STG_FT_MDTR_MNSL_1
where	(1=1)