DROP TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_OUTL;

CREATE TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_OUTL
(
	OUTLET_cod VARCHAR2(10),
	outlet_des VARCHAR2(50),
	OUTLET_add VARCHAR2(120),
	chan_cod VARCHAR2(4),
	BRICK_cod VARCHAR2(10),
	CNPJ VARCHAR2(14),
	COMPLE_C VARCHAR2(50),
	REGI_PTR VARCHAR2(50),
	REDE_IND VARCHAR2(1),
	CATEGORIA VARCHAR2(50),
	BAIRRO VARCHAR2(50),
	LOGRADOURO VARCHAR2(50),
	TELEFONE VARCHAR2(50),
	CEP VARCHAR2(8),
	Cidade VARCHAR2(50),
	UF VARCHAR2(2)
);