DROP TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_PACK;

CREATE TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_PACK
(
	pack_cod VARCHAR2(10),
	PROD_COD VARCHAR2(5),
	pack_desc VARCHAR2(90),
	PACK_LNCH VARCHAR2(8),
	std_fact VARCHAR2(8),
	dsg_fact VARCHAR2(8),
	Class4_cod VARCHAR2(6),
	App3_cod VARCHAR2(3),
	EAN VARCHAR2(13)
);