DROP TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_PERI_MDTRM;

CREATE TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_PERI_MDTRM
(
	PERIOD_COD VARCHAR2(8),
	WEEK1 VARCHAR2(2),
	WEEK2 VARCHAR2(2),
	WEEK3 VARCHAR2(2),
	WEEK4 VARCHAR2(2),
	WEEK5 VARCHAR2(2),
	WEEK6 VARCHAR2(2),
	WEEK7 VARCHAR2(2)
);