DROP TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_PROD;

CREATE TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_PROD
(
	prod_cod VARCHAR2(5),
	Prod_desc VARCHAR2(50),
	manu_cod VARCHAR2(5),
	MANU_DESC VARCHAR2(18),
	MANU_SHORT VARCHAR2(3),
	prod_lnch VARCHAR2(8),
	MARK_COD VARCHAR2(1),
	GENE_COD VARCHAR2(1)
);