DROP TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_REPO;

CREATE TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_REPO
(
	PACK_CODE VARCHAR2(10),
	PROD_Code VARCHAR2(5),
	report_cod VARCHAR2(2),
	report_des VARCHAR2(30),
	colu_cod VARCHAR2(5)
);