DROP TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_WHOL;

CREATE TABLE BI.TB_WRK_FFFC_BRA_SMPMDTR_WHOL
(
	WHS_COD VARCHAR2(10),
	WHS_DESC VARCHAR2(25),
	WHS_ID VARCHAR2(14),
	WHS_TYPE VARCHAR2(30),
	WHS_STATE VARCHAR2(30),
	WHS_CITY VARCHAR2(50)
);