DROP TABLE BI.TB_WRK_PBS_FFF_BRA_NPS_APP;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_NPS_APP
(	
	PACK_CD VARCHAR2(50),
	PACK_DESC VARCHAR2(250),
	PRODUCT_CONCTR_CD VARCHAR2(50),
	APP1_CD VARCHAR2(50),
	APP1_DESC VARCHAR2(250),
	APP2_CD VARCHAR2(50),
	APP2_DESC VARCHAR2(250),
	APP3_CD VARCHAR2(50),
	APP3_DESC VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT PRODUCT_CONCTR_CD||PACK_CD,PACK_CD,COUNT(*) FROM BI.TB_WRK_PBS_FFF_BRA_NPS_APP
GROUP BY PRODUCT_CONCTR_CD||PACK_CD,PACK_CD
HAVING COUNT(*) > 1 

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_NPS_APP
WHERE PRODUCT_CONCTR_CD = '0500500000000MG20ACY'