DROP TABLE BI.TB_WRK_PBS_FFF_BRA_NPS_CHANNEL;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_NPS_CHANNEL
(	
	CHANNEL_ID VARCHAR2(5),
	CHANNEL_DESC VARCHAR2(100),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_NPS_CHANNEL