DROP TABLE BI.TB_WRK_PBS_FFF_BRA_NPS_CONCTR;	

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_NPS_CONCTR
(
	PACK_CD VARCHAR2(10),
	PACK_DESC VARCHAR2(250),
	PRODUCT_DESC VARCHAR2(250),
	PRODUCT_CONCTR_CD VARCHAR2(50),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI.TB_WRK_PBS_FFF_BRA_NPS_CONCTR
WHERE PRODUCT_CONCTR_CD = '03044000000MG0D25DGM'