DROP TABLE BI.TB_WRK_PBS_FFF_BRA_NPS;

CREATE TABLE BI.TB_WRK_PBS_FFF_BRA_NPS
(	
	DISPENSED_PACK_CD VARCHAR2(100),
	RX_COUNT VARCHAR2(100),
	DISPENSED_QTY VARCHAR2(100),
	SPECIALTY_CD VARCHAR2(100),
	CHANNEL_CD VARCHAR2(100),
	IMS_TERRITORY_CD VARCHAR2(100),
	PERIOD_CD VARCHAR2(100),
	SWITCH_CD VARCHAR2(100),
	PSCR_PRODUCT_CONCTR_CD  VARCHAR2(100),
	DT_ULT_ATZ timestamp
);

SELECT PERIOD_CD,COUNT(*) FROM BI.TB_WRK_PBS_FFF_BRA_NPS
GROUP BY PERIOD_CD
ORDER BY 1 ASC