SELECT ERROR_MESSAGE
FROM SNP_LPI_STEP_LOG
WHERE (I_LP_STEP,I_LP_INST) IN
(SELECT I_LP_STEP,
  I_LP_INST
FROM snp_lpi_exc_log
WHERE I_LP_INST = (SELECT I_LP_INST FROM SNP_LP_INST WHERE GLOBAL_ID = '<%=odiRef.getLoadPlanInstance("BATCH_GUID")%>')
AND NB_RUN      = <%=odiRef.getLoadPlanInstance("RESTART_ATTEMPTS")%>
AND SESS_NO     = <%=odiRef.getSession( "SESS_NO" )%>
)


SELECT ERROR_MESSAGE
FROM SNP_LPI_STEP_LOG
WHERE (I_LP_STEP,I_LP_INST) IN
(SELECT I_LP_STEP,
  I_LP_INST
FROM snp_lpi_exc_log
WHERE SESS_NO = 158
)


SELECT
ERROR_MESSAGE FROM
snp_STEP_LOG
WHERE NNO IN (
SELECT MIN(NNO)
FROM snp_STEP_LOG
WHERE SESS_NO = <%=odiRef.getSession( "SESS_NO" )%>
AND STEP_STATUS = 'E')
AND SESS_NO = <%=odiRef.getSession( "SESS_NO" )%>