
DROP TABLE BI_MDM.TB_DM_DSTRB;


CREATE TABLE BI_MDM.TB_DM_DSTRB
(
SK_DSTRB varchar2(10) PRIMARY KEY,
DS_DSTRB varchar2(150),
DS_CNPJ_DSTRB VARCHAR2(20),
DS_DSTRB_CNSLD VARCHAR(50),
DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_DSTRB ORDER BY 1 asc