
DROP TABLE BI_MDM.TB_DM_PDV;

CREATE TABLE BI_MDM.TB_DM_PDV
(
SK_PDV VARCHAR2(50) PRIMARY KEY,
DS_PDV VARCHAR2(150),
DS_CNPJ_PDV VARCHAR2(20),
DS_TP_ENDR VARCHAR2(250),
DS_ENDR VARCHAR2(250),
DS_CMPLMNT VARCHAR2(250),
DS_BRR VARCHAR2(250),
DS_CEP VARCHAR2(15),
DS_CDD VARCHAR2(50),
DS_UF VARCHAR2(50),
DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_PDV;