DROP TABLE BI_MDM.TB_DM_PRDT;

CREATE TABLE BI_MDM.TB_DM_PRDT
(
SK_PRDT VARCHAR2(20) PRIMARY KEY,
SK_PRDT_FCC VARCHAR2(50),
DS_PRDT_FCC VARCHAR2(100),
DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_PRDT


WHERE SK_PRDT_FCC = '057434'
