DROP TABLE BI_MDM.TB_DM_PRSCRBD_PRDCT;	

CREATE TABLE BI_MDM.TB_DM_PRSCRBD_PRDCT
(
	SK_PRSCRBD_PRDCT VARCHAR2(100) PRIMARY KEY,
	DS_PRSCRBD_PRDCT VARCHAR2(100),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_PRSCRBD_PRDCT
