DROP TABLE BI_MDM.TB_DM_DSPNSD_PRDT;	

CREATE TABLE BI_MDM.TB_DM_DSPNSD_PRDT
( 
	SK_DSPNSD_PRDT VARCHAR2(250) PRIMARY KEY,
	DS_DSPNSD_PRDT VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_DSPNSD_PRDT