DROP TABLE BI_MDM.TB_DM_APP_PCK;	

CREATE TABLE BI_MDM.TB_DM_APP_PCK
(	SK_PCK VARCHAR2(10) PRIMARY KEY,
	DS_PCK VARCHAR2(150),
	SK_APP3 VARCHAR2(3),
	DT_ULT_ATZ timestamp
);

ALTER TABLE BI_MDM.TB_DM_APP_PCK ADD CONSTRAINT FK_SK_APP3_PCK
    FOREIGN KEY (SK_APP3)
    REFERENCES BI_MDM.TB_DM_APP (SK_APP3)
    
    
SELECT * FROM BI_MDM.TB_DM_APP_PCK
ORDER BY 1 ASC

COMMIT

