DROP TABLE BI_MDM.TB_DM_DSPNSD_PCKS;	

DELETE FROM BI_MDM.TB_DM_DSPNSD_PCKS;

COMMIT

CREATE TABLE BI_MDM.TB_DM_DSPNSD_PCKS
(
	SK_DSPNSD_PCKS VARCHAR2(250) PRIMARY KEY,
	DS_DSPNSD_PCKS VARCHAR2(250),
	DS_DSPNSD_PCKS_NDF VARCHAR2(250),
	DS_PCK_LNCH VARCHAR2(250),
	DS_PRDCT_LNCH VARCHAR2(250),
	DS_MRKT_TP VARCHAR2(250),
	DS_STD_FCT VARCHAR2(250),
	DS_DSG_FCT VARCHAR2(250),
	DS_GNRC_BRND VARCHAR2(250),
	DS_CMBND_MLCL VARCHAR2(250),
	DS_BRND_NM VARCHAR2(250),
	DS_STGH_VL VARCHAR2(250),
	DS_STGH_MSR VARCHAR2(250),
	DS_FML VARCHAR2(250),
	DS_PRDCT_TP_2 VARCHAR2(250),
	FLG_CNTRLLD_PRSCRPTN VARCHAR2(250),
	FLG_HRBL_MDCN VARCHAR2(250),
	FLG_GVRNMNT_PRGRM VARCHAR2(250),
	FLG_KIT VARCHAR2(250),
	SK_DSPNSD_PRDT VARCHAR2(250),
	SK_ATC4 VARCHAR2(250),
	SK_NEC4 VARCHAR2(250),
	SK_PRDCT_CNCTR VARCHAR2(250),
	DT_ULT_ATZ timestamp
);

SELECT * FROM BI_MDM.TB_DM_DSPNSD_PCKS

ALTER TABLE BI_MDM.TB_DM_DSPNSD_PCKS ADD CONSTRAINT FK_DSPNSD_PRDT
    FOREIGN KEY (SK_DSPNSD_PRDT)
    REFERENCES BI_MDM.TB_DM_DSPNSD_PRDT (SK_DSPNSD_PRDT)
    
ALTER TABLE BI_MDM.TB_DM_DSPNSD_PCKS ADD CONSTRAINT FK_ATC
    FOREIGN KEY (SK_ATC4)
    REFERENCES BI_MDM.TB_DM_ATC (SK_ATC4)
    
ALTER TABLE BI_MDM.TB_DM_DSPNSD_PCKS ADD CONSTRAINT FK_NEC
    FOREIGN KEY (SK_NEC4)
    REFERENCES BI_MDM.TB_DM_NEC (SK_NEC4)
    
ALTER TABLE BI_MDM.TB_DM_DSPNSD_PCKS ADD CONSTRAINT FK_PRDCT_CNCTR
    FOREIGN KEY (SK_PRDCT_CNCTR)
    REFERENCES BI_MDM.TB_DM_CNCTR (SK_PRDCT_CNCTR)
    
ALTER TABLE BI_MDM.TB_DM_DSPNSD_PCKS DROP CONSTRAINT FK_PRDCT_CNCTR