DROP TABLE BI_MDM.TB_DM_PRSCRBD_PRDCT_CNCTR;	

CREATE TABLE BI_MDM.TB_DM_PRSCRBD_PRDCT_CNCTR
(
	SK_PRSCRBD_PRDCT_CNCTR VARCHAR2(100) PRIMARY KEY,
	DS_PRSCRBD_PRDCT_CNCTR VARCHAR2(100),
	SK_PRSCRBD_PRDCT VARCHAR2(100),
	SK_MNFCTRR VARCHAR2(100),
	DS_PRDCT_LNCH VARCHAR2(100),
	DS_MRKT_TP VARCHAR2(100),
	DS_BRND_NM VARCHAR2(100),
	DS_STGH_VL VARCHAR2(100),
	DS_STGH_MSR  VARCHAR2(100),
	DT_ULT_ATZ timestamp
);

ALTER TABLE BI_MDM.TB_DM_PRSCRBD_PRDCT_CNCTR ADD CONSTRAINT FK_PRSCRBD_PRDCT
    FOREIGN KEY (SK_PRSCRBD_PRDCT)
    REFERENCES BI_MDM.TB_DM_PRSCRBD_PRDCT (SK_PRSCRBD_PRDCT)

ALTER TABLE BI_MDM.TB_DM_PRSCRBD_PRDCT_CNCTR ADD CONSTRAINT FK_MNFCTRR
    FOREIGN KEY (SK_MNFCTRR)
    REFERENCES BI_MDM.TB_DM_MNFCTRR (SK_MNFCTRR)
    

SELECT * FROM BI_MDM.TB_DM_PRSCRBD_PRDCT_CNCTR
